### ISSUE TITLE
1.8.7 shows 1.8.6 in "Help..." dialog

### ISSUE THREAD

**Issue by sunjw** [oviradoi/npp-explorer-plugin#10]
1.8.7 shows 1.8.6 in "Help..." dialog
![nppexplorer-1 8 7](https://user-images.githubusercontent.com/846335/67174405-7dd21300-f3f4-11e9-9645-1022d91ec101.png)

**Comment by oviradoi** [comment]
This was fixed in 1.8.8
Thanks for reporting this
