### ISSUE TITLE
Requires Visual C++ Redistributable

### ISSUE THREAD

**Issue by pryrt** [oviradoi/npp-explorer-plugin#12]
As [discussed in the NPP Community Forum](https://community.notepad-plus-plus.org/topic/19330/explorer-dll-the-specified-module-could-not-be-found/4), this plugin requires the Microsoft Visual C++ Redistributable, and people who don't happen to have that installed will not be able to get this plugin to work.

This should be mentioned in the README.  (In a few minutes, I will be submitting a PR to fix this)

**Comment by oviradoi** [comment]
Thanks for reporting this. I will take a look to see if I can remove that dependency from the plugin.
