### ISSUE TITLE
Favorites Not In Alphabetical Order

### ISSUE THREAD

**Issue by Skibicki** [oviradoi/npp-explorer-plugin#18]
Windows 8.1
Notepad++ 7.8.6
Explorer Plugin 1.8.9.0

When adding favorites some are in proper order but others are not.

**Comment by oviradoi** [comment]
Thanks for reporting this.

The sorting algorithm used to be case-sensitive and it would put uppercase items before lowercase items, ignoring the actual text.

This is fixed in version 1.9.0.
