### ISSUE TITLE
Issue when deleted session or favorites with N++ 7.6.6

### ISSUE THREAD

**Issue by artlogika** [oviradoi/npp-explorer-plugin#2]
If I tried to delete session or favorites from explorer window I got errors like on these screenshots. 

[before I deleted](https://drive.google.com/open?id=1DvenZBLIb026lNKIpzPSKBM_AqNg0u0e)
[after deleting](https://drive.google.com/open?id=1oWnvJNzqn87LbHo06pZ5-itfcrLty9r4)

I can see only in N++ 7.6.6, both desktop and portable version. In previous N++ version I cannot see that issue.

Thanks!

**Comment by oviradoi** [comment]
I have tried and I have managed to reproduce this problem.

I will let you know when I manage to fix it.

Thanks for reporting the problem!

**Comment by oviradoi** [comment]
I have fixed the problem and I released a new version.

I will create a pull request to include the new version in Notepad++'s Plugin Manager, but this will take some time.

If you want, you can manually install the fixed version from here: [Version 1.8.6](https://github.com/oviradoi/npp-explorer-plugin/releases/tag/v1.8.6)
