### ISSUE TITLE
Creating a Favorites group with a space in the name leads to Notepad++ freezing

### ISSUE THREAD

**Issue by duckfarts** [oviradoi/npp-explorer-plugin#20]
To recreate the issue:
* Open the **Favorites** panel.
* Right-click on **[Files]**, select **New Group...**, and enter a name with a space in it then click **OK**..
* With a file open, click on the **Link Current File...** button, double-click on **[Files]**, select your group and click **OK**.
* Notepad++ will freeze and you will need to forcibly close it. After reopening Notepad++, the newly created group will be gone.

**Comment by oviradoi** [comment]
Thanks for reporting this. The issue has been fixed in the latest release.
