### ISSUE TITLE
No -/+ expansion icon in New Element dialog for Favorites

### ISSUE THREAD

**Issue by duckfarts** [oviradoi/npp-explorer-plugin#21]
When adding a new link or folder by clicking the **Link Current File...** or **Link Current Folder...* buttons, the **[Files]** and **[Folder]** icons will not show a -/+ expansion icon next to them if there are additional groups inside them. You can still double-click them, but it's not clear there may be subgroups.

![image](https://user-images.githubusercontent.com/24978179/92858532-c2113c00-f428-11ea-9f2b-cbfa86d97c40.png)

On the other hand, if you double-click on them and you have groups with subgroups, those *will* have a -/+ expansion icon to indicate they have subgroups.

![image](https://user-images.githubusercontent.com/24978179/92858670-ecfb9000-f428-11ea-9b73-63a0cbab9350.png)

**Comment by oviradoi** [comment]
Thanks for reporting this. I have added the expand/collapse buttons in the latest release.
