### ISSUE TITLE
View doesn´t open

### ISSUE THREAD

**Issue by Klugschieter** [oviradoi/npp-explorer-plugin#24]
Hi,
I have a problem with this plugin since I updated N++ to 7.9.2.
It installs without problems. After starting N++ the two icons (Explorer and Favorites) are in the toolbar, but don´t open the Explorer/Favorites-Tree on the lefthand side of the window.
Only the textfield slides maybe 3px to the right, but no Explorer/Favorites Window shows up.
"Hide menu bar" is not active.
Plugin Deinstall + Install new doesn´t solve the problem.

I have the plugin for years, but never had that problem.
Can somebody help please?

Greets

**Comment by oviradoi** [comment]
Hey. It sounds like the Explorer panel is visible, but is verry narrow (2-3 pixels wide).

You can fix this by grabbing the splitter that lies between the text area and the Explorer panel, and dragging it to the right.

If that does not work, you can try to reset Explorer's saved position by closing Notepad++, deleting this file `%APPDATA%\Notepad++\plugins\Config\Explorer.ini` and then opening Notepad++ again.

Please let me know if this solved your problem.

**Comment by Klugschieter** [comment]
Hey,
thanks for the fast and useful answer!
I had to delete the Explorer.ini, after that the splitter became visible and I could drag it to the right.
So I´m happy again with my most used Notepad++-Plugin
