### ISSUE TITLE
Doesn't show drive letter A

### ISSUE THREAD

**Issue by daniel-scholten** [oviradoi/npp-explorer-plugin#25]
It shows drive B, but not drive A. When a program is unable to list drive letters before C, both A and B are affected normally. And what's special here, too, is that I cannot navigate to A:\ through a symbolic link on another drive.

7.9.1 (64-bit), Windows 10, Explorer 1.9.3

**Comment by oviradoi** [comment]
Thanks for reporting this.

There was a bug in the drive letter enumeration code.

I have fixed it in the latest release.
