### ISSUE TITLE
Access Vioaltion when NPP starts

### ISSUE THREAD

**Issue by badabing2005** [oviradoi/npp-explorer-plugin#27]
This plugin is causing Access Violation when Npp starts up.
Any ideas what night be the issue?

![image](https://user-images.githubusercontent.com/22603312/149674068-b5ce7daa-0fa6-4d48-952c-6d9165bf8539.png)

**Comment by oviradoi** [comment]
Sorry, I don't have enough information to figure out what is going on.

The only guess I have is that maybe the plugin's config files have been corrupted somehow.

You can try to open `%APPDATA%\Notepad++\plugins\Config` and delete `Explorer.ini` and `Favorites.dat`, then restart Notepad++ and see if this fixes the crash.

If this does not work, please post some more details:
* Notepad++ version, and whether it's 32 or 64 bit
* Explorer plugin version
* Windows version
* A dump file of Notepad++ while this error is displayed
  * You can create a dump file from Task Manager by right-clicking Notepad++ and choosing "Create dump file"
  * Here is a page showing how to do it: https://support.kaspersky.com/common/diagnostics/12401
  * The dump file might be large, so you might want to compress it and upload it to some file host (like wetransfer.com) and then post the link here.

**Comment by badabing2005** [comment]
Thanks @oviradoi  for the follow up
It wasn't a corrupt `Explorer.ini` file, it was `Favorites.dat`
For reference here's what was the content of it.
```
[Folders]
Expand=0

[Files]
Expand=1

#LINK
```

PS: Explorer.ini got automatically recreated, but not the Favorites.dat
Many thanks for your assistance

**Comment by badabing2005** [comment]
Ok I see it gets created when closing the NPP
This issue can be closed.
Thanks
