### ISSUE TITLE
Saved favorites do not open with Return key

### ISSUE THREAD

**Issue by GwenDragon** [oviradoi/npp-explorer-plugin#28]
The Favorites panel does not open saved favorites in NPP-Explorer panel with keyboard. 

Steps to reproduce:
1. Have already some favorite f.ex. folders added (works only with mouse)
1. Open Favorites panel with Ctrl+Alt+Shift+V
1. Select a favorite with Cursor ↓ key
1. Hit Return key to open folder in NPP-Explorer panel

**Current**
No reaction

**Expected**
Folder is shown in Explorer panel

**Additional**
Opening a saved favorite does only work with mouse

**Debug info**
```
Notepad++ v8.3   (32-bit)
Build time : Feb  3 2022 - 03:35:48
Path : P:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.469
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll Explorer.dll JSLintNpp.dll JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll RegexTrainer.dll RunMe.dll Tidy2.dll 
```

**Comment by oviradoi** [comment]
This has been fixed in version 1.9.5.0
