### ISSUE TITLE
Suggestion: Consider supporting "." or "," for the "Dynamic x,x b/k/M" display mode.

### ISSUE THREAD

**Issue by ZStoner** [oviradoi/npp-explorer-plugin#31]
In the Options, there's an option to display a decimal point for file sizes.Ki
But it appears to only use the "0,000" style for decimals, rather than "0.000".
This setting could be auto-detected by the user's locale, for the "Number Decimal Separator".

**Comment by oviradoi** [comment]
This was implemented in version 1.9.6.

I have rewritten the logic that calculates the file size. Now it respects the user's globalization preferences for the thousands and decimal separator.
