### ISSUE TITLE
Round file size or display file size as decimal

### ISSUE THREAD

**Issue by Kristine1975** [oviradoi/npp-explorer-plugin#32]
(Thank you for your plugin, it's exactly what I need!)

Notepad++ v8.3.3 64 Bit on Windows 10, with Explorer Plugin 1.9.4.0. In the Explorer options I have selected "View 'Long' List" and size as "kBytes". The size of an 802-byte file is shown as "0 kB"

Thoughts/ideas:
- Round the file size up: "1 kB"
- Display the file size as decimal: "0.8 kB"
- Only display "0 kB" when the file is truly empty

**Comment by oviradoi** [comment]
This was implemented in version 1.9.6.

I have rewritten the logic that calculates the file size. Now it respects the user's globalization preferences for the thousands and decimal separator. Also, it will round up the file size to 1 kb. Files that are exactly 0 bytes are shown as 0.
