### ISSUE TITLE
v1.9.6 dark mode not working

### ISSUE THREAD

**Issue by gilgrissom** [oviradoi/npp-explorer-plugin#36]
v1.9.6 Colors don't follow Dark Mode in both Favorites and Explorer pane

![Capture269](https://user-images.githubusercontent.com/10052441/217580249-833018a1-94c2-4188-ae41-10fa78d972e2.png)

v1.9.5 Colors and Dark Mode work as expected

![Capture270](https://user-images.githubusercontent.com/10052441/217583148-95fff22f-704e-4a22-ad3b-38ad5d970180.png)

**Comment by gilgrissom** [comment]
Thanks for your feedback.
I tried several times to restart NP++; v1.9.5 works as expected, v1.9.6 background shows white
Also with different permutations of the Preferences Dark Mode Setting (Dark or Follow Windows) and "Solarized" Theme

I also created a new instance of NP++ from a clean download from NP website and just installed Explorer plugin... same behavior.

**Comment by oviradoi** [comment]
Can you tell me what version of Notepad++ you are using? Is it the latest 8.4.9?

**Comment by oviradoi** [comment]
This should be fixed in the latest release, v1.9.7

**Comment by gilgrissom** [comment]
It's fixed... thanks
