### ISSUE TITLE
1.9.6, file list background color for selected items

### ISSUE THREAD

**Issue by klaus101** [oviradoi/npp-explorer-plugin#37]
With update 1.9.5 to 1.9.6 the colors for the file list selection bar was changed:
white font on medium blue background ($00D77800) instead of black font on skyblue background ($00FFE8CE).

At least for me the readability of the selected item(s) does suffer a lot, sigh, i find it harder to read.
Additionally, there is no more a "hover" bg color (hottrack bg color on the lines where the mouse is moving over).

I'd really like to have the "old" behaviour back. But how other than to go back to the 1.9.5? Might that be optional?

See picture attached.

![plugin_explorer](https://user-images.githubusercontent.com/31130146/218196422-21821b6b-bf0f-4b4e-8c0a-9e5313e615cc.jpg)

**Comment by oviradoi** [comment]
Thanks for reporting the issue. This should be fixed in the latest release, v.1.9.7

**Comment by klaus101** [comment]
Thank you very much for your attention and the fast fix.  It's fine again!
