### ISSUE TITLE
Any way to change Explorer background color?

### ISSUE THREAD

**Issue by yenrenART** [oviradoi/npp-explorer-plugin#42]
Hi, the Explorer background color used to be white in an older version. It is now black and I really prefer the white background. Is there a way/option to change it back to white? Thanks!

**Comment by oviradoi** [comment]
The background color of the Explorer plugin is now the same as the background color of Notepad++.

You can change the background color to anything you like by using the Style Configurator window. You need to select the Global Styles category, and the Default Style in the lists. After that, you can edit the background color on the right.

![image](https://github.com/oviradoi/npp-explorer-plugin/assets/8641811/d41d4533-0695-42cf-ad4a-fb2d85fcf7e7)

**Comment by yenrenART** [comment]
Thank you very much, now it is how I prefer it :) I will take note of this so I don't forget for future installs.
