### ISSUE TITLE
Access violation 

### ISSUE THREAD

**Issue by elecherf** [oviradoi/npp-explorer-plugin#44]
Hi,

The plugin does not load with the latest notepad++ releases.

Here is the popup error at notepad++ startup

![image](https://github.com/oviradoi/npp-explorer-plugin/assets/10000902/57810c89-3ce8-4764-873c-08d464fb14a4)

![image](https://github.com/oviradoi/npp-explorer-plugin/assets/10000902/56b62da6-7306-4428-805e-572e24259a91)

Please help

Thanks a lot

**Comment by oviradoi** [comment]
Hello. The most likely cause for this issue is a corrupted Favorites.dat file.

Please try to delete your Favorites.dat file and let me know if the issue goes away.

This issue has been reported previously here: https://github.com/oviradoi/npp-explorer-plugin/issues/27

**Comment by elecherf** [comment]
Hello,

The problem disappeared and I don't know under which condition. The Favorites.dat was recreated.

Thank you
