### ISSUE TITLE
Windows dialog out of reach

### ISSUE THREAD

**Issue by SullyPanda76cl** [oviradoi/npp-explorer-plugin#5]
Hi... In an involuntary movement, just drag the window out of desktop...
Can't reach its title bar with mouse.
Where does this plugin store its windows position configuration?

thanks!

![npp_fav](https://user-images.githubusercontent.com/44233071/59147853-d2896a00-89ce-11e9-9b6c-0722e12d0b6a.png)

**Comment by oviradoi** [comment]
Duplicate of #4
