### ISSUE TITLE
Notepad++ crashes when changing Date Options

### ISSUE THREAD

**Issue by ma-schroeder** [oviradoi/npp-explorer-plugin#6]
Hi there,

when changing the Date Format to "D.M.Y HH:MM" in Explorer Options the whole application crashes. The option reverts back to the default date format after starting Notepad++ again.
I'm using the newest version 1.8.6 and it has worked in the old 1.8.2 version.

Thanks

**Comment by oviradoi** [comment]
Thanks for reporting the bug. I have fixed it in commit 373993e62b5ab038af319b211705d6a91ff56863

**Comment by ma-schroeder** [comment]
Nice, thanks
