### ISSUE TITLE
Change font size of explorer window

### ISSUE THREAD

**Issue by laxamar** [oviradoi/npp-explorer-plugin#8]
I'm looking for a way to change the font size of the explorer window. On a very high resolution screen (4K), the fonts are too small and almost illegible I have not found a way to increase ONLY the explorer font size.

**Comment by oviradoi** [comment]
@laxamar Notepad++, including the explorer window, scales automatically according to the Windows display scaling. The explorer text should match the size of Notepad++'s menu bar.

Could you attach a screenshot so I can see how small the text is on a 4K display?

Thanks

**Comment by laxamar** [comment]
Sure,

Thanks for looking into this.

Here you go:

**Comment by oviradoi** [comment]
Hey @laxamar 

Thanks for responding. It looks like you replied to the email in your inbox with an image attachment, but the attachment was not sent to the github issue.

Could you please attach the image by replying directly on the github issue?

Thanks

**Comment by laxamar** [comment]
Sure, let me try to do it here.
![notepadexplorer4k](https://user-images.githubusercontent.com/2382057/81483368-90763300-91f2-11ea-8e2c-ee22a11f6800.png)

Hope this works.

Thanks

**Comment by oviradoi** [comment]
Thanks for the reply.

As I suspected, the font size is the same as the one for the Notepad++ menu bar. If you increase your Windows scaling in the display settings, the size will increase and it will make all apps easier to read.

I guess adding a font size setting in the Explorer plugin would also help. I will keep this in mind as a feature to add in the future.

**Comment by oviradoi** [comment]
Hey @laxamar .
I have implemented the custom font size option in the latest release: https://github.com/oviradoi/npp-explorer-plugin/releases/tag/v1.9.2

**Comment by laxamar** [comment]
Thank you so much. Works great. If my eyes could kiss you :-D

Take care
